version = 0.1

[default.deploy.parameters]
stack_name = "NutriTrack-2"
resolve_s3 = true
s3_prefix = "NutriTrack-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true

[default.global.parameters]
region = "us-west-2"
